quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=pocuser
quarkus.datasource.password=pocPassword
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pocdb

quarkus.hibernate-orm.database.generation.create-script-source=metadata
# OR simply use the specific management property:
quarkus.hibernate-orm.schema-generation.database.generation=validate
